[default.extend-words]
# do not correct the following strings:
fpr = "fpr"
PLAD = "PLAD"
Childs = "Childs"
OT = "OT"
ND = "ND"
GIR = "GIR"
AKS = "AKS"
FRE = "FRE"
Ein = "Ein"
# `indexin` is a function name
indexin = "indexin"

[files]
# do not check the following files:
extend-exclude = ["references.md"]
